title:            maiatoday
description:      summary of my GitHub repos
url:              #"http://www.maiatoday.net"
signoff:          "maia"
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
  - name:         Art
    url:          http://www.maiatoday.co.za
    external:     true
  - name:         GitHub
    url:          http://github.com/maiatoday
    external:     true
permalink:        pretty
markdown:         kramdown
highlighter:      rouge
gems:
  - jekyll-gist
kramdown:
  input: GFM
