title: maiatoday
description: > # this means to ignore newlines until "baseurl:"
  maiatoday code exploration
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://maiatoday.net" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: "maiatoday" #if your site has a twitter account, enter it here

# Author Settings
author: Maia Grotepass # add your name
author-img: maia.png # add your photo
about-author: Android dev ❤️ Kotlin. # add description
social-twitter: maiatoday # add your Twitter handle
social-github: maiatoday # add your Github handle
social-linkedin: maiagrotepass # add your Linkedin handle
social-email: "maiatoday+io@gmail.com" # add your Email address

# Disqus
discus-identifier: maiatoday # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
